version: "3.8"
services:
  flask-app:
    image: ${DOCKER_HUB_CREDS_USR}/flaskapp:latest
    build: .
    container_name: flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}


  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - type: volume
      source: mysql
      target: /var/lib/mysql

volumes:
  mysql: