pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDS_USR = credentials("DOCKER_HUB_CREDS_USR")
        DOCKER_HUB_CREDS_PSW = credentials("DOCKER_HUB_CREDS_PSW")
        // DATABASE_URI=credentials("DATABASE_URI")
    }
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                sh "bash jenkins/build.sh"
            }
        }
        stage('Push') {
            steps {
                sh "bash jenkins/push.sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
    }

}